services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_USE_MOCK=true
    container_name: gmania-app
    ports:
      - "8080:80"
    restart: unless-stopped